export type Citation = {
  document_id: string;
  title: string;
  url: string | null;
  quote: string;
};

export type GroundedAnswer = {
  intent: string;
  summary: string;
  missing_context: string[];
  recommended_action: string;
  answer: string;
  draft_reply: string;
  citations: Citation[];
  confidence: "low" | "medium" | "high";
  response_language?: "id" | "en";
  verification_status?: "verified" | "not_verified";
  // Internal warning shown separately from the safe answer.
  safety_warning?: string;
  // True when draft_reply is empty because the Notion article itself is
  // unfinished (missing Customer Reply / Customer Safe Summary / Customer
  // Action) — a knowledge-authoring gap, not something the customer needs
  // to supply. Distinguishes that from missing_context, which is data CS
  // still needs to collect from the customer. Optional/undefined = false.
  knowledge_gap?: boolean;
  // Guidance below is derived deterministically from the cited Notion article
  // (see lib/case-guidance.ts), never generated by the model.
  case_understanding?: {
    received: string[];
    missing: string[];
    stage: "info_received" | "cs_result" | "escalate";
  };
  next_actions?: string[];
  escalate_when?: string[];
  knowledge_status?: "complete" | "partial" | "unavailable";
  knowledge_missing?: string[];
  last_verified?: string;
  knowledge_stale?: boolean;
};

export type KnowledgeDocument = {
  id: string;
  title: string;
  url: string | null;
  content: string;
  category: string | null;
  synced_at: string;
};
