export type Category = "SOP" | "FAQ" | "Troubleshooting" | "Template";
export type KnowledgeItem = { id: string; title: string; category: Category; excerpt: string; content: string; source: string; synced: string; };
export const categories: Array<"All" | Category> = ["All", "SOP", "FAQ", "Troubleshooting", "Template"];
export const knowledgeItems: KnowledgeItem[] = [
  { id: "password-reset", title: "Panduan Reset Password", category: "FAQ", excerpt: "Langkah aman untuk membantu client melakukan reset password.", content: "1. Verifikasi email client.\n2. Arahkan client ke halaman reset password.\n3. Pastikan password baru memenuhi standar keamanan.\n4. Minta client mencoba login kembali.", source: "Notion · Customer Support FAQ", synced: "11 Aug 2026, 09:42" },
  { id: "payment-failed", title: "Troubleshooting Pembayaran Gagal", category: "Troubleshooting", excerpt: "Checklist investigasi ketika pembayaran client gagal diproses.", content: "Periksa status transaksi, metode pembayaran, dan pesan error. Jangan meminta credential atau data kartu lengkap dari client. Eskalasikan transaksi yang tetap gagal sesuai SOP.", source: "Notion · Troubleshooting Guide", synced: "11 Aug 2026, 09:42" },
  { id: "response-delay", title: "SOP Penanganan Keterlambatan Respons", category: "SOP", excerpt: "Standar komunikasi untuk kasus yang membutuhkan investigasi lebih lanjut.", content: "Akui pertanyaan client, jelaskan bahwa kasus sedang diperiksa, berikan estimasi waktu yang realistis, dan catat kebutuhan follow-up sesuai SOP.", source: "Notion · SOP Customer Support", synced: "11 Aug 2026, 09:42" },
  { id: "greeting-template", title: "Template Balasan Pembuka", category: "Template", excerpt: "Template pembuka yang ramah dan konsisten untuk percakapan baru.", content: "Halo, terima kasih telah menghubungi Timedoor. Kami akan membantu memeriksa kebutuhan Anda. Mohon informasikan detail kendala yang dialami.", source: "Notion · Response Templates", synced: "11 Aug 2026, 09:42" },
];
export const defaultDraft = "Halo, terima kasih telah menghubungi kami. Kami memahami kendala yang Anda alami. Kami akan membantu memeriksa detailnya sesuai panduan yang tersedia. Mohon menunggu sementara kami melakukan pengecekan lebih lanjut.";
